### ISSUE TITLE
Need Home screen icon for site survey, inventory management, schedules.

### ISSUE THREAD

**Issue by ahar101** [wastewater-intelligence-network/win-mobile-rn#25]

**Comment by upperwal** [comment]
Available here: https://drive.google.com/drive/folders/11MCtVJ36sQot5YnuujtF6F7tksWCxvo_?usp=sharing

**Comment by upperwal** [comment]
@ahar101  Icons for site survey list and collection point map are available in the drive.

**Comment by ahar101** [comment]
thanks.
